== Plugin Konfiguration

IMPORTANT: Pour ne pas installer le broker Mosquitto localement, c'est à dire sur la machine où tourne Jeedom, commencer par décocher la case _Installer Mosquitto localement_.

Après installation du plugin, l'activer. Celui-ci prend quelques minutes pour installer les dépendances. Le suivi détaillé de la progression est possible via le log `_jMQTT_dep_` qui apparait au bout d'un moment en rafraichissant la page.

Par défaut le plugin est configuré pour s'inscrire au broker Mosquitto installé localement. Si cette configuration convient, cliquer sur Sauvegarder. Le status du démon passe à OK. Rafraichir la page pour faire apparaitre le fichier de log `_jMQTT_`.

TIP: Configurer le niveau de log minimum à Info pour que le fichier de log apparaisse la première fois et avoir des informations intéressantes. Sauvegarder et relancer le démon pour rendre le changement actif.

IMPORTANT: Il peut arriver que l'installation du plugin se bloque. Cela se produit si le serveur apache est relancé pendant l'installation (voir log `_jMQTT_dep_`). Pour se débloquer, se connecter à sa station Jeedom et supprimer le fichier `/tmp/jeedom/jMQTT/progress_dep.txt`.

Pour particulariser la configuration du plugin, les paramètres sont:

  - Installer Mosquitto localement: cocher cette case pour que jMQTT se charge de l'installation locale du broker Mosquitto. Si votre broker est distant, décocher la case.
  - IP de Mosquitto: adresse IP du broker (par défaut localhost i.e. sur la machine hébergeant Jeedom).
  - Port de Mosquitto: port du broker (1883 par défaut).
  - Identifiant de connexion: identifiant avec lequel le plugin s'inscrit auprès du broker (jeedom par défaut).
  - Compte et mot de passe de connexion: il est possible d'ajouter un compte et mot de passe si la connexion le nécessite (pas d'authentification par défaut).
  - Topic de souscription en mode inclusion automatique des équipments: topic de souscription automatique à partir duquel le plugin va découvrir les équipements de manière automatique, nous y revenons dans la partie équipements (défaut #, i.e. tous les topics).

La sauvegarde de la configuration relance le démon et la souscription au broker MQTT avec les nouveaux paramètres.

TIP: Il est conseillé d'activer la gestion automatique du démon. Ainsi, en cas de problème (e.g. perte de connexion au broker), Jeedom relancera le démon toutes les 5 minutes, aux minutes fixes 00, 05, 10, ...