== Plugin Konfiguration

Après installation du plugin, l'activer. Celui-ci prend quelques minutes pour installer les dépendances. Le suivi de la progression est possible via le log `_jMQTT_dep_` qui apparait au bout d'un moment en rafraichissant la page.

Par défaut le plugin est configuré pour s'inscrire au broker Mosquitto qu'il a lui même installé sur la machine où tourne Jeedom. Si cette configuration convient, cliquer sur Sauvegarder. Le status du démon passe à OK. Rafraichir la page pour faire apparaitre le fichier de log `_jMQTT_`.

TIP: Configurer le niveau de log minimum à Info pour que le fichier de log apparaisse la première fois et avoir des informations intéressantes.

Pour particulariser la configuration du plugin, les paramètres sont:

  - IP de Mosquitto: adresse IP du broker (par défaut 127.0.0.1 i.e. sur la machine hébergeant Jeedom).
  - Port de Mosquitto: port du broker (1883 par défaut).
  - Identifiant de connexion: identifiant avec lequel le plugin s'inscrit auprès du broker (jeedom par défaut).
  - Compte et mot de passe de connexion: il est possible d'ajouter un compte et mot de passe si la connexion le nécessite (pas d'authentification par défaut).
  - Topic root: topic de souscription automatique à partir duquel le plugin va découvrir les équipements de manière automatique, nous y revenons dans la partie équipements (défaut #, i.e. tous les topics).
  - QOS: qualité de service associée au topic root de souscription automatique (voué à disparaitre dans une future version du plugin, défaut 1).

La sauvegarde de la configuration relance le démon et la souscription au broker MQTT avec les nouveaux paramètres.

TIP: Il est conseillé d'activer la gestion automatique du démon. Ainsi, en cas de problème (e.g. perte de connexion au broker), Jeedom relancera le démon toutes les 5 minutes, aux minutes fixes 00, 05, 10, ...