[flake8]
paths = ../../resources/jmqttd_api/
# select = E9,F63,F7,F82
count
show-source
# extend-ignore = E203
# exclude = .git,__pycache__,docs/source/conf.py,old,build,dist
max-complexity = 10
max-line-length = 127
