version: 1
disable_existing_loggers: False

formatters:
    withCallTrace:
        format: "[%(asctime)s]%(levelname)-10s %(threadName)-11s %(name)-15s %(funcName)20s() L%(lineno)-4d %(message)s   call_trace=%(pathname)s L%(lineno)-4d"
    withThread:
        format: "[%(asctime)s]%(levelname)-10s %(threadName)-11s %(name)-15s %(funcName)20s() : %(message)s"
    withFunction:
        format: "[%(asctime)s]%(levelname)-10s %(name)-20s %(funcName)20s() : %(message)s"
    normal:
        format: "[%(asctime)s]%(levelname)-10s %(name)-15s : %(message)s"

filters:
    logFilter:
        (): utils.LogFilter

handlers:
    consoleHandler:
        class:     logging.StreamHandler
        # level:     DEBUG
        # formatter: withCallTrace
        # formatter: withThread
        formatter: withFunction
        # formatter: normal
        stream:    ext://sys.stdout
        filters:   [logFilter]

root:
    level: DEBUG
    # level: WARNING # TODO disable DEBUG
    handlers: [consoleHandler]

# loggers:
#     asyncio:
#         level: WARNING
#     concurrent:
#         level: WARNING
#     fastapi:
#         level: WARNING
#     # jmqtt:
#         # level: DEBUG
#     uvicorn:
#         level: WARNING
#     # pydantic:
#     #     level: WARNING
#     # gunicorn:
#     #     level: WARNING
