var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.findInternal=function(a,b,d){a instanceof String&&(a=String(a));for(var e=a.length,c=0;c<e;c++){var f=a[c];if(b.call(d,f,c,a))return{i:c,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");$jscomp.checkStringArgs=function(a,b,d){if(null==a)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,d){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===d&&(d=b.length);d=Math.max(0,Math.min(d|0,b.length));for(var c=a.length;0<c&&0<d;)if(b[--d]!=a[--c])return!1;return 0>=c}},"es6","es3");var refreshTimeout;
function callPluginAjax(a){$.ajax({async:void 0==a.async?!0:a.async,global:!1,type:"POST",url:"plugins/jMQTT/core/ajax/jMQTT.ajax.php",data:a.data,dataType:"json",error:function(a,d,e){handleAjaxError(a,d,e)},success:function(b){"ok"!=b.state?$("#div_alert").showAlert({message:b.result,level:"danger"}):"function"===typeof a.success&&a.success(b.result)}})}
function initPluginUrl(a,b,d){a=void 0===a?["id","saveSuccessFull","removeSuccessFull","hash"]:a;b=void 0===b?"":b;d=void 0===d?"":d;var e=getUrlVars(),c="index.php?",f;for(f in e)0>$.inArray(f,a)&&("?"!=c.substr(-1)&&(c+="&"),c+=f+"="+e[f].replace("#",""));""!=b&&(c+="&id="+b);""!=document.location.hash&&0>$.inArray("hash",a)&&(c+=document.location.hash);""!=d&&(c+=d);return c}
function refreshEqLogicPage(){function a(){""!=$(".eqLogicAttr[data-l1key=id]").value()?(tab=null,document.location.toString().match("#")&&(tab="#"+document.location.toString().split("#")[1],tab="#"!=tab?$('a[href="'+tab+'"]'):null),$('.eqLogicDisplayCard[data-eqlogic_id="'+$(".eqLogicAttr[data-l1key=id]").value()+'"]').click(),tab&&tab.click()):$(".eqLogicAction[data-action=returnToThumbnailDisplay]").click()}modifyWithoutSave?bootbox.confirm("{{La page a \u00e9t\u00e9 modifi\u00e9e. Etes-vous s\u00fbr de vouloir la recharger sans sauver ?}}",
function(b){b&&a()}):a()}$(document).ready(function(){"#commandtab"==document.location.hash&&$("#menu-bar").show();$(".eqLogicAction[data-action=refreshPage]").removeAttr("href").off("click").on("click",function(a){a.stopPropagation();refreshEqLogicPage()})});$("#bt_addMQTTInfo").on("click",function(a){addCmdToTable({type:"info"});modifyWithoutSave=!0});$("#bt_addMQTTAction").on("click",function(a){addCmdToTable({type:"action"});modifyWithoutSave=!0});
$(".eqLogicAction[data-action=healthMQTT]").on("click",function(){$("#md_modal").dialog({title:"{{Sant\u00e9 jMQTT}}"});$("#md_modal").load("index.php?v=d&plugin=jMQTT&modal=health").dialog("open")});$("#table_cmd").delegate(".listEquipementAction","click",function(){var a=$(this);jeedom.cmd.getSelectModal({cmd:{type:"action"}},function(b){a.closest("tr").find(".cmdAttr[data-l1key=configuration][data-l2key="+a.attr("data-input")+"]").value(b.human)})});
$("#table_cmd").delegate(".listEquipementInfo","click",function(){var a=$(this);jeedom.cmd.getSelectModal({cmd:{type:"info"}},function(b){a.closest("tr").find(".cmdAttr[data-l1key=configuration][data-l2key="+a.data("input")+"]").atCaret("insert",b.human);modifyWithoutSave=!0})});$("#bt_classic").on("click",function(){refreshEqLogicPage();$("#bt_classic").removeClass("btn-default").addClass("btn-primary");$("#bt_json").removeClass("btn-primary").addClass("btn-default")});
$("#bt_json").on("click",function(){refreshEqLogicPage();$("#bt_json").removeClass("btn-default").addClass("btn-primary");$("#bt_classic").removeClass("btn-primary").addClass("btn-default")});$('.nav-tabs a[href="#eqlogictab"],.nav-tabs a[href="#brokertab"]').on("click",function(){$("#menu-bar").hide()});$('.nav-tabs a[href="#commandtab"]').on("click",function(){$("#menu-bar").show()});
$("#table_cmd").sortable({axis:"y",cursor:"move",items:".cmd",placeholder:"ui-state-highlight",tolerance:"intersect",forcePlaceholderSize:!0});
$(".eqLogicAction[data-action=add_jmqtt]").on("click",function(){if("undefined"===typeof $(this).attr("brkId"))var a={type:"broker",brkId:-1},b="{{Nom du broker ?}}";else a={type:"eqpt",brkId:$(this).attr("brkId")},b="{{Nom de l'\u00e9quipement ?}}";bootbox.prompt(b,function(b){null!==b&&jeedom.eqLogic.save({type:eqType,eqLogics:[$.extend({name:b},a)],error:function(a){$("#div_alert").showAlert({message:a.message,level:"danger"})},success:function(a){var b=initPluginUrl();modifyWithoutSave=!1;b+=
"&id="+a.id+"&saveSuccessFull=1";loadPage(b)}})})});
$(".eqLogicAction[data-action=remove_jmqtt]").on("click",function(){function a(){jeedom.eqLogic.remove({type:eqType,id:$(".eqLogicAttr[data-l1key=id]").value(),error:function(a){$("#div_alert").showAlert({message:a.message,level:"danger"})},success:function(){var a=initPluginUrl();modifyWithoutSave=!1;loadPage(a+"&removeSuccessFull=1")}})}if(void 0!=$(".eqLogicAttr[data-l1key=id]").value()){var b="broker"==$(".eqLogicAttr[data-l2key=type]").value()?"broker":"module";bootbox.confirm("{{Etes-vous s\u00fbr de vouloir supprimer}} "+
("broker"==b?"{{le broker}}":"{{l'\u00e9quipement}}")+" <b>"+$(".eqLogicAttr[data-l1key=name]").value()+"</b> ?",function(d){d&&("broker"==b?bootbox.confirm('<table><tr><td style="vertical-align:middle;font-size:2em;padding-right:10px"><span class="label label-warning"><i class="fa fa-warning"</i></span></td><td style="vertical-align:middle">{{Tous les \u00e9quipements associ\u00e9s au broker vont \u00eatre supprim\u00e9s}}...<br><b>{{\u00cates vous s\u00fbr ?}}</b></td></tr></table>',function(b){b&&
a()}):a())})}else $("#div_alert").showAlert({message:"{{Veuillez d'abord s\u00e9lectionner un}} "+eqType,level:"danger"})});
$(".eqLogicAction[data-action=move_broker]").on("click",function(){var a=$(".eqLogicAttr[data-l1key=id]").value(),b=$("#broker").val();void 0!=a&&void 0!=b&&bootbox.confirm('<table><tr><td style="vertical-align:middle;font-size:2em;padding-right:10px"><span class="label label-warning"><i class="fa fa-warning"</i></span></td><td style="vertical-align:middle">{{Vous \u00eates sur le point de changer l\'\u00e9quipement de broker}}.<br>{{\u00cates vous s\u00fbr ?}}</td></tr></table>',function(d){d&&callPluginAjax({async:!1,
data:{action:"moveToBroker",id:a,brk_id:b},success:function(a){window.location.reload()}})})});
$(".applyTemplate").off("click").on("click",function(){callPluginAjax({data:{action:"getTemplateList"},success:function(a){var b='<label class="control-label">{{Choisissez un template : }}</label> <select class="bootbox-input bootbox-input-select form-control" id="applyTemplateSelector">';for(var d in a)b+='<option value="'+d+'">'+d+"</option>";b+='</select><br><label class="control-label">{{Saisissez le Topic de base : }}</label> ';a=$(".eqLogicAttr[data-l1key=logicalId]").value();if(a.endsWith("#")||
a.endsWith("+"))a=a.substr(0,a.length-1);a.endsWith("/")&&(a=a.substr(0,a.length-1));bootbox.confirm({title:"{{Appliquer un Template}}",message:b+('<input class="bootbox-input bootbox-input-text form-control" autocomplete="off" type="text" id="applyTemplateTopic" value="'+a+'"><br><br>')+'<label class="control-label">{{Que voulez-vous faire des commandes existantes ?}}</label> <div class="radio"><label><input type="radio" name="applyTemplateCommand" value="1" checked="checked">{{Les conserver / Mettre \u00e0 jour}}</label></div><div class="radio"><label><input type="radio" name="applyTemplateCommand" value="0">{{Les supprimer d\'abord}}</label> </div>',
callback:function(a){a&&callPluginAjax({data:{action:"applyTemplate",id:$(".eqLogicAttr[data-l1key=id]").value(),name:$("#applyTemplateSelector").val(),topic:$("#applyTemplateTopic").val(),keepCmd:$("[name='applyTemplateCommand']:checked").val()},success:function(a){$(".eqLogicDisplayCard[data-eqLogic_id="+$(".eqLogicAttr[data-l1key=id]").value()+"]").click()}})}})}})});
$(".createTemplate").off("click").on("click",function(){callPluginAjax({data:{action:"getTemplateList"},success:function(a){bootbox.prompt({title:"Nom du nouveau template ?",callback:function(a){null!==a&&callPluginAjax({data:{action:"createTemplate",id:$(".eqLogicAttr[data-l1key=id]").value(),name:a},success:function(a){$(".eqLogicDisplayCard[data-eqLogic_id="+$(".eqLogicAttr[data-l1key=id]").value()+"]").click()}})}})}})});
function printEqLogic(a){var b=1;if(0!=$("#bt_json.active").length){for(var d=function(b){var c=-1,p=b.lastIndexOf("{");if(0<=p){father_topic=b.substring(0,p);d(father_topic);var h=f(l,father_topic);void 0!==h&&(c=h.treegrid_id)}h=f(l,b);if(void 0===h&&(h=f(a.cmd,b),void 0!==h)){jeedom.cmd.execute({async:!1,id:h.id,cache:0,notify:!1,success:function(a){h.value=a}});try{var g=JSON.parse(h.value)}catch(r){}"object"===typeof g?e(h.configuration.topic,g,c):m(h,c)}},e=function(a,d,f){c(a,d,void 0===f?
-1:f);f=b-1;for(i in d)"object"===typeof d[i]?e(a+"{"+i+"}",d[i],f):c(a+"{"+i+"}",d[i],f)},c=function(b,c,d){c="object"===typeof c?JSON.stringify(c):c;var e=f(a.cmd,b);void 0===e?m({configuration:{topic:b},isHistorized:"0",isVisible:"1",type:"info",subType:"string",value:c},d):(e.value=c,m(e,d))},f=function(a,b){a=a.filter(function(a){return a.configuration.topic==b});if(0<a.length)return a[0]},k=function(a,b){return a.find(function(a){return a==b})},m=function(a,c){c=void 0===c?-1:c;a.treegrid_id=
b++;0<c&&(a.treegrid_parent_id=c);l.push(a)},l=[],q=$jscomp.makeIterator(a.cmd),g=q.next();!g.done;g=q.next())g=g.value,k(l,g)||("info"==g.type?d(g.configuration.topic):m(g));a.cmd=l;$("#table_cmd").sortable("disable")}else{k=$jscomp.makeIterator(a.cmd);for(g=k.next();!g.done;g=k.next())g=g.value,g.treegrid_id=b++;$("#table_cmd").sortable("enable")}void 0==a.configuration.brkId||0>a.configuration.brkId||"eqpt"!=a.configuration.type&&"broker"!=a.configuration.type?($(".toDisable").addClass("disabled"),
$(".typ-brk").hide(),$(".typ-std").show()):"broker"==a.configuration.type?($(".toDisable").removeClass("disabled"),$(".typ-std").hide(),$(".typ-brk").show(),$("#mqtttopic").prop("readonly",!0),k="jMQTT_"+(a.name.replace(" ","_")||"jeedom"),$("input[name=rd_logupdate]").attr("data-l1key","log::level::"+k),$(".bt_plugin_conf_view_log").attr("data-log",k),$(".bt_plugin_conf_view_log").html('<i class="fa fa fa-file-text-o"></i> '+k),refreshDaemonInfo(),jeedom.config.load({configuration:$("#div_broker_log").getValues(".configKey")[0],
plugin:"jMQTT",error:function(a){$("#div_alert").showAlert({message:a.message,level:"danger"})},success:function(a){$("#div_broker_log").setValues(a,".configKey")}})):"eqpt"==a.configuration.type&&($(".toDisable").removeClass("disabled"),$(".typ-brk").hide(),$(".typ-std").show(),$("#mqtttopic").prop("readonly",!1));var n=$("#broker");n.empty();$.each(eqBrokers,function(a,b){n.append(new Option(b,a))});n.val(a.configuration.brkId)}
function saveEqLogic(a){var b=$("#div_broker_log").getValues(".configKey")[0];$.isEmptyObject(b)||(a.loglevel=b);for(b=a.cmd.length-1;0<=b;b--)""==a.cmd[b].id&&""==a.cmd[b].name&&a.cmd.splice(b,1);return a}
function addCmdToTable(a){isset(a)||(a={configuration:{}});isset(a.configuration)||(a.configuration={});var b=0!=$("#bt_json.active").length;if("info"==init(a.type)){var d=function(b){$(".treegrid-"+a.treegrid_id+" .form-control[data-key=value]").value(b)},e="1"==init(a.configuration.virtualAction)?"disabled":"",c='<tr class="cmd treegrid-'+a.treegrid_id;b&&0<a.treegrid_parent_id&&(c+=" treegrid-parent-"+a.treegrid_parent_id);c+='" data-cmd_id="'+init(a.id)+'">';c+='<td class="fitwidth"><span class="cmdAttr" data-l1key="id"></span>';
c=b?c+'<span style="display:none;" class="cmdAttr" data-l1key="order"></span></td>':c+"</td>";c+='<td><textarea class="cmdAttr form-control input-sm" data-l1key="name" style="height:65px;" placeholder="{{Nom de l\'info}}"></textarea></td>';c+="<td>";c+='<input class="cmdAttr form-control type input-sm" data-l1key="type" value="info" disabled style="margin-bottom:5px;width:120px;" />';c+='<span class="cmdAttr subType" subType="'+init(a.subType)+'"></span>';c+="</td><td>";c+='<textarea class="cmdAttr form-control input-sm" data-l1key="configuration" data-l2key="topic" style="height:65px;" '+
e+' placeholder="{{Topic}}"></textarea>';c+="</td><td>";c+='<textarea class="form-control input-sm" data-key="value" style="height:65px;" '+e+' placeholder="{{Valeur}}" readonly=true></textarea>';c+='</td><td class="fitwidth">';c+='<input class="cmdAttr form-control input-sm" data-l1key="unite" placeholder="{{Unit\u00e9}}"></td><td>';is_numeric(a.id)?(c+='<span><label class="checkbox-inline"><input type="checkbox" class="cmdAttr checkbox-inline" data-l1key="isHistorized" checked/>{{Historiser}}</label></span> ',
c+='<span><label class="checkbox-inline"><input type="checkbox" class="cmdAttr checkbox-inline" data-l1key="isVisible" checked/>{{Afficher}}</label></span> ',c+='<span><label class="checkbox-inline"><input type="checkbox" class="cmdAttr checkbox-inline" data-l1key="display" data-l2key="invertBinary"/>{{Inverser}}</label></span> ',c+="</td><td>",c+='<a class="btn btn-default btn-xs cmdAction" data-action="configure"><i class="fas fa-cogs"></i></a> ',c+='<a class="btn btn-default btn-xs cmdAction" data-action="test"><i class="fas fa-rss"></i> {{Tester}}</a>'):
c+="</td><td>";void 0!=a.id&&void 0==a.configuration.irremovable&&(c+=' <a class="btn btn-default btn-xs cmdAction pull-right" data-action="remove"><i class="fas fa-minus-circle"></i></a>');c+="</td></tr>";$("#table_cmd tbody").append(c);$("#table_cmd tbody tr:last").setValues(a,".cmdAttr");isset(a.type)&&$("#table_cmd tbody tr:last .cmdAttr[data-l1key=type]").value(init(a.type));jeedom.cmd.changeType($("#table_cmd tbody tr:last"),init(a.subType));d(a.value);void 0!=a.id&&(b||jeedom.cmd.execute({id:a.id,
cache:0,notify:!1,success:function(a){d(a)}}),jeedom.cmd.update[a.id]=function(a){d(a.display_value)})}"action"==init(a.type)&&(c='<tr class="cmd treegrid-'+a.treegrid_id+'" data-cmd_id="'+init(a.id)+'">',c+="<td>",c+='<span class="cmdAttr" data-l1key="id"></span>',c+="</td>",c+="<td>",c+='<div class="row">',c+='<div class="col-sm-4">',c+='<a class="cmdAction btn btn-default btn-sm" data-l1key="chooseIcon" style="padding-left:5px;padding-right:5px;"><i class="fa fa-flag"></i>  Ic\u00f4ne</a>',c+=
'<span class="cmdAttr" data-l1key="display" data-l2key="icon" style="margin-left:5px;"></span>',c+="</div>",c+='<div class="col-sm-8">',c+='<input class="cmdAttr form-control input-sm" data-l1key="name">',c+="</div>",c+="</div>",c+='<select class="cmdAttr form-control tooltips input-sm" data-l1key="value" style="display:none;margin-top:5px;margin-right:10px;" title="{{Valeur par d\u00e9faut de la commande}}">',c+='<option value="">Aucune</option>',c+="</select>",c+="</td>",c+="<td>",c+='<input class="cmdAttr form-control type input-sm" data-l1key="type" value="action" disabled style="margin-bottom:5px;width:120px;" />',
c+='<span class="cmdAttr subType" subType="'+init(a.subType)+'" style=""></span>',c+="</td>",c+="<td>",c+='<textarea class="cmdAttr form-control input-sm" data-l1key="configuration" data-l2key="topic" style="height:65px;"'+e+' placeholder="{{Topic}}"></textarea><br/>',c+="</td><td>",c+='<textarea class="cmdAttr form-control input-sm" data-l1key="configuration" data-l2key="request" style="height:30px;" '+e+' placeholder="{{Valeur}}"></textarea>',c+='<a class="btn btn-default btn-sm cursor listEquipementInfo" data-input="request" style="margin-top:5px;margin-left:5px;"><i class="fa fa-list-alt "></i> {{Rechercher \u00e9quipement}}</a>',
c+="</select></span>",c+="</td><td></td><td>",c+='<span><label class="checkbox-inline"><input type="checkbox" class="cmdAttr checkbox-inline" data-l1key="isVisible" checked/>{{Afficher}}</label></span><br> ',c+='<span><label class="checkbox-inline"><input type="checkbox" class="cmdAttr checkbox-inline" data-l1key="configuration" data-l2key="retain"/>{{Retain}}</label></span><br> ',c+='<span class="checkbox-inline">{{Qos}}: <input class="tooltips cmdAttr form-control input-sm" data-l1key="configuration" data-l2key="Qos" placeholder="{{Qos}}" title="{{Qos}}" style="width:50px;display:inline-block;"></span> ',
c+="</td>",c+="<td>",is_numeric(a.id)&&(c+='<a class="btn btn-default btn-xs cmdAction expertModeVisible" data-action="configure"><i class="fa fa-cogs"></i></a> ',c+='<a class="btn btn-default btn-xs cmdAction" data-action="test"><i class="fa fa-rss"></i> {{Tester}}</a>'),c+='<a class="btn btn-default btn-xs cmdAction pull-right" data-action="remove"><i class="fa fa-minus-circle"></i></a></td>',c+="</tr>",$("#table_cmd tbody").append(c),c=$("#table_cmd tbody tr:last"),jeedom.eqLogic.builSelectCmd({id:$(".eqLogicAttr[data-l1key=id]").value(),
filter:{type:"info"},error:function(a){$("#div_alert").showAlert({message:a.message,level:"danger"})},success:function(b){c.find(".cmdAttr[data-l1key=value]").append(b);c.setValues(a,".cmdAttr");jeedom.cmd.changeType(c,init(a.subType))}}));b&&$(".tree").treegrid({initialState:"expanded",expanderExpandedClass:"fas fa-minus",expanderCollapsedClass:"fas fa-plus"})}
$("body").off("jMQTT::cmdTopicMismatch").on("jMQTT::cmdTopicMismatch",function(a,b){a=$("#div_cmdMsg").is(":empty")||$("#div_cmdMsg").is(":hidden")?"{{La commande}} <b>"+b.cmd_name+"</b> {{a un topic incompatible du topic d'inscription de l'\u00e9quipement}} <b>"+b.eqlogic_name+"</b>.":"{{Plusieurs commandes ont des topics incompatibles du topic d'inscription de l'\u00e9quipement}} <b>"+b.eqlogic_name+"</b>.";$("#div_cmdMsg").showAlert({message:a,level:"warning"})});
$("body").off("jMQTT::cmdAdded").on("jMQTT::cmdAdded",function(a,b){a=$("#div_cmdMsg").is(":empty")||$("#div_cmdMsg").is(":hidden")?"{{La commande}} <b>"+b.cmd_name+"</b> {{est ajout\u00e9e \u00e0 l'\u00e9quipement}} <b>"+b.eqlogic_name+"</b>.":"{{Plusieurs commandes sont ajout\u00e9es \u00e0 l'\u00e9quipement}} <b>"+b.eqlogic_name+"</b>.";modifyWithoutSave||$(".eqLogic").is(":visible")&&$(".eqLogicAttr[data-l1key=id]").value()!=b.eqlogic_id||0!=$('div[role="dialog"]').filter(":visible").length||
!b.reload?$("#div_cmdMsg").showAlert({message:a,level:"warning"}):($("#div_cmdMsg").showAlert({message:a+" {{La page va se r\u00e9actualiser automatiquement}}.",level:"warning"}),void 0===refreshTimeout&&(refreshTimeout=setTimeout(function(){refreshTimeout=void 0;$(".eqLogicAction[data-action=refreshPage]").click()},3E3)))});
function configureIncludeModeDisplay(a,b){1==b?($(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"]").attr("data-mode",1),$(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"].card span").text("{{Arr\u00eater l'inclusion}}"),$(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"]").addClass("include"),$("#div_inclusionModeMsg").showAlert({message:"{{Mode inclusion automatique pendant 2 \u00e0 3min. Cliquez sur le bouton pour forcer la sortie de ce mode avant.}}",level:"warning"})):
($(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"]").attr("data-mode",0),$(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"].card span").text("{{Mode inclusion}}"),$(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"]").removeClass("include"),$("#div_inclusionModeMsg").hideAlert())}
function setIncludeModeActivation(a,b){if("ok"==b)$(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"]").removeClass("disableCard").on("click",changeIncludeMode);else $(".eqLogicAction[data-action=changeIncludeMode][brkId="+a+"]").addClass("disableCard").unbind()}
function changeIncludeMode(){var a=$(this);1==a.attr("data-mode")?configureIncludeModeDisplay(a.attr("brkId"),0):configureIncludeModeDisplay(a.attr("brkId"),1);callPluginAjax({data:{action:"changeIncludeMode",mode:a.attr("data-mode"),id:a.attr("brkId")}})}
$("body").off("jMQTT::EventState").on("jMQTT::EventState",function(a,b){showDaemonInfo(b);setIncludeModeActivation(b.brkId,b.state);$('.eqLogicDisplayCard[jmqtt_type="broker"][data-eqlogic_id="'+b.brkId+'"] img').attr("src","plugins/jMQTT/resources/images/node_broker_"+b.state+".svg")});$("body").off("jMQTT::disableIncludeMode").on("jMQTT::disableIncludeMode",function(a,b){configureIncludeModeDisplay(b.brkId,0)});
$("body").off("jMQTT::eqptAdded").on("jMQTT::eqptAdded",function(a,b){a="{{L'\u00e9quipement}} <b>"+b.eqlogic_name+"</b> {{vient d'\u00eatre inclu}}";modifyWithoutSave||$(".eqLogic").is(":visible")||0!=$('div[role="dialog"]').filter(":visible").length?$("#div_newEqptMsg").showAlert({message:a+".",level:"warning"}):($("#div_newEqptMsg").showAlert({message:a+". {{La page va se r\u00e9actualiser automatiquement}}.",level:"warning"}),void 0===refreshTimeout&&(refreshTimeout=setTimeout(function(){refreshTimeout=
void 0;window.location.reload()},3E3)))});
