name: Check PHP

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  check-php:
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false
      max-parallel: 2
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1', '8.2']
        jeedom-branch: ['V4-stable', 'alpha']

    steps:
      - name: Checkout Jeedom ${{ matrix.jeedom-branch }}
        uses: actions/checkout@v3
        with:
          repository: jeedom/core
          ref: ${{ matrix.jeedom-branch }}

      - name: Create plugins folder
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/plugins/jMQTT

      - name: Checkout jMQTT
        uses: actions/checkout@v3
        with:
          path: plugins/jMQTT

      - name: Install dependencies
        run: composer update --working-dir=${GITHUB_WORKSPACE}/plugins/jMQTT/resources/JsonPath-PHP

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpstan
        env:
          debug: true

      - name: Run PHPStan
        run: phpstan analyse -c plugins/jMQTT/.github/phpstan/config.neon
