name: "Automated translations"
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - uses: Mips2648/plugins-translations@main
        with:
          source_language: "fr_FR"
          target_languages: "fr_FR,en_US"
          # target_languages: "en_US,es_ES,de_DE,it_IT,pt_PT"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
          # include_empty_translation: true
          generate_source_language_translations: true
          # debug: true
